name: Wen-Hao Lue
description: "Engineer, jazz musician, foodie"
url: https://wenhaolue.com
email: wenhao@wenhaolue.com
permalink: pretty
plugins:
  - jekyll-sitemap
pygments: true
relative_permalinks: false
exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "config.rb",
    "Rakefile",
    "Procfile.local",
  ]

google_analytics:
  account: UA-12654814-1
disqus:
  id: wlue
